project:
  type: website
  output-dir: docs/

website:
  title: "Como Raspar?"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  revealjs:
    theme: night
    css: styles.css
    toc: true




